apiVersion: v1
kind: Service
metadata:
  name: postgres-name-replica
  namespace: default
  labels:
    app.kubegres.io/replication-role: replica
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app.kubegres.io/replication-role: replica
